export const PRODUCT_ACTION_TYPES = {
    // SET_PRODUCTS: 'products/SET_PRODUCTS',
    FETCH_PRODUCT_START: 'producst/FETCH_PRODUCT_START',
    FETCH_PRODUCT_SUCCESS: 'producst/FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILED: 'producst/FETCH_PRODUCT_FAILED',
}